# Generated by Django 4.2 on 2023-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remote',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
