# Generated by Django 4.2 on 2023-04-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_remote_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='left_position_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='button',
            name='top_position_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
